### ISSUE TITLE
Error with latest downloaded update

### ISSUE THREAD

**Issue by iwab1** [BAndysc/WoWDatabaseEditor#100]
**Describe the bug**
I'm unable to open the editor since the latest update on 11/18. The process will appear briefly in Task Manager when I attempt to open then will instantly close; no window will open
When I open the 2021.1 version that's downloadable from Github, it will give me the error log from the current version. This error log only appears in the 2021.1 version when I first attempt to open the latest version released on 11/18
I've downloaded Runtime 6 and 5, I hope that isn't the issue somehow.

**Version (commit hash)**
50f620e

**To Reproduce**
1. Open newest version of the editor
2. Newest version does not open
3. Open the 2021.1 version downloadable on GitHub, see error log.

Here's the error log:

Unity.ResolutionFailedException: Resolution failed with error: Exception has been thrown by the target of an invocation.

For more detailed information run Unity in debug mode: new UnityContainer().AddExtension(new Diagnostic())
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> WDE.MPQ.MpqParsingException: Invalid MPQ format. Must be '1' or '3'.
   at WDE.MPQ.MpqArchive.ParseArchiveHeader() in C:\projects\wowdatabaseeditor\WDE.MPQ\MpqArchive.Parsing.cs:line 71
   at WDE.MPQ.MpqArchive..ctor(String path, Stream stream, Boolean cleanupStreamOnDispose) in C:\projects\wowdatabaseeditor\WDE.MPQ\MpqArchive.cs:line 43
   at WDE.MPQ.MpqArchive.Open(String path) in C:\projects\wowdatabaseeditor\WDE.MPQ\MpqArchive.cs:line 84
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at WDE.MPQ.Services.MpqService.Open() in C:\projects\wowdatabaseeditor\WDE.MPQ\Services\MpqService.cs:line 31
   at WDE.MapRenderer.GameViewModel..ctor(IMpqService mpqService, IDbcStore dbcStore, IMapDataProvider mapData, ITaskRunner taskRunner, IMessageBoxService messageBoxService, IDatabaseClientFileOpener databaseClientFileOpener, IGameView gameView, GameViewSettings settings) in C:\projects\wowdatabaseeditor\WDE.MapRenderer\GameViewModel.cs:line 99
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Unity.Processors.ConstructorProcessor.<>c__DisplayClass16_0.<GetResolverDelegate>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.UnityContainer.<>c__DisplayClass113_0.<OptimizingFactory>b__0(BuilderContext& c)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.<>c.<.ctor>b__73_2(BuilderStrategy[] chain, BuilderContext& context)
   at Unity.Builder.BuilderContext.Resolve(Type type, String name, InternalRegistration registration)
   at Unity.UnityContainer.ResolveEnumerable[TElement](Func`4 resolve, String name)+MoveNext()
   at WoWDatabaseEditorCore.Managers.DocumentManager..ctor(IEventAggregator eventAggregator, IMessageBoxService messageBoxService, IEnumerable`1 tools) in C:\projects\wowdatabaseeditor\WoWDatabaseEditor\Managers\DocumentManager.cs:line 38
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Unity.Processors.ConstructorProcessor.<>c__DisplayClass16_0.<GetResolverDelegate>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.UnityContainer.<>c__DisplayClass113_0.<OptimizingFactory>b__0(BuilderContext& c)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.<>c.<.ctor>b__73_2(BuilderStrategy[] chain, BuilderContext& context)
   at Unity.Builder.BuilderContext.Resolve(Type type, String name, InternalRegistration registration)
   at Unity.Builder.BuilderContext.Resolve(Type type, String name)
   at Unity.Strategies.BuildKeyMappingStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.<>c.<.ctor>b__73_2(BuilderStrategy[] chain, BuilderContext& context)
   at Unity.Builder.BuilderContext.Resolve(Type type, String name, InternalRegistration registration)
   at Unity.Builder.BuilderContext.Resolve(Type type, String name)
   at Unity.Builder.BuilderContext.Resolve(ParameterInfo parameter, Object value)
   at Unity.Processors.ParametersProcessor`1.<>c__DisplayClass7_0.<CreateParameterResolvers>b__0(BuilderContext& context)
   at Unity.Processors.ConstructorProcessor.<>c__DisplayClass16_0.<GetResolverDelegate>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.UnityContainer.<>c__DisplayClass113_0.<OptimizingFactory>b__0(BuilderContext& c)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.<>c.<.ctor>b__73_1(BuilderContext& context)
   --- End of inner exception stack trace ---
   at Unity.UnityContainer.<>c.<.ctor>b__73_1(BuilderContext& context)
   at Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, ResolverOverride[] overrides)
   at Prism.Unity.Ioc.UnityContainerExtension.Resolve(Type type) in C:\projects\wowdatabaseeditor\Prism.Avalonia\src\Prism.Unity.Avalonia\Ioc\UnityContainerExtension.cs:line 57
   at Prism.Ioc.IContainerProviderExtensions.Resolve[T](IContainerProvider provider)
   at WoWDatabaseEditorCore.Avalonia.App.Initialize() in C:\projects\wowdatabaseeditor\WoWDatabaseEditorCore.Avalonia\App.xaml.cs:line 255
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 310
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 147
   at WoWDatabaseEditorCore.Avalonia.Program.Main(String[] args) in C:\projects\wowdatabaseeditor\WoWDatabaseEditorCore.Avalonia\Program.cs:line 34

COMMIT=50f620e3cd63253ecbb365e994d11ebdc5d70851  
BRANCH=master  
VERSION=0.1.1081  
BUILD_VERSION=1081  
UPDATE_SERVER=https://dbeditor.ovh  
MARKETPLACE=default 
PLATFORM=Windows

**Comment by BAndysc** [comment]
Hi, thanks for the report, are you using any custom MPQ patches? It looks like, and they seem to be of some newer unknown format to the editor.

Anyway, I have updated the editor so that it doesn't crash it. Please download and try now: https://github.com/BAndysc/WoWDatabaseEditor/releases/tag/2021.3

**Comment by grip244** [comment]
Same issue, different error. 

`System.IO.FileNotFoundException: Could not load file or assembly 'WDE.SmartScriptEditor.Avalonia, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'WDE.SmartScriptEditor.Avalonia, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(String name) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 243
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetResAsmAndPath(Uri uri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 192
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 203
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri, Uri baseUri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 101
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 50
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 287
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 680
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
   at WoWDatabaseEditorCore.Avalonia.App.!XamlIlPopulate(IServiceProvider , App ) in D:\WowDBE\WoWDatabaseEditorCore.Avalonia\App.xaml:line 55
   at WoWDatabaseEditorCore.Avalonia.App.!XamlIlPopulateTrampoline(App )
   at WoWDatabaseEditorCore.Avalonia.App.Initialize() in D:\WowDBE\WoWDatabaseEditorCore.Avalonia\App.xaml.cs:line 249
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 310
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 147
   at WoWDatabaseEditorCore.Avalonia.Program.Main(String[] args) in D:\WowDBE\WoWDatabaseEditorCore.Avalonia\Program.cs:line 34
`

**Comment by grip244** [comment]
Building myself.

**Comment by BAndysc** [comment]
@grip244 so the building process with Visual Studio became slightly broken lately. Using `dotnet publish` manually worked fine, but VS had problems.

Now I have got rid of .net 5.0, cleaned up the solution and projects a bit and building from VS 2022 should work just fine now. Before I close the issue, could you please try again building it yourself? (Please clone the project again, or at least remove all bin/ obj/ folders, because they might interfere with current project).

**Comment by grip244** [comment]
Thank you, I would like to point out, I needed to remove the -r win7-64, in order to build. Otherwide I was left with a release>net 6.0, with no .exe.

**Comment by BAndysc** [comment]
Indeed, after the last commit it needs to be at least `win8-x64` or newer. Will change that in readme, thanks
