### ISSUE TITLE
Spell Name not show

### ISSUE THREAD

**Issue by gonzo1247** [BAndysc/WoWDatabaseEditor#116]
**Describe the bug**
For some time now, the names of the spells are no longer displayed. Unfortunately, I can't say exactly since which update. It doesn't matter whether it's a spell from the spell.dbc or from the spell_dbc database.
I set the path to the DBCs correctly.

![wow_editor_spell_name](https://user-images.githubusercontent.com/640311/162265578-a237bc6b-35a8-453b-8f13-b2cf0b83a748.jpg)

**Version (commit hash)**
Please include what was the WoW Database Editor version (commit hash). **If you downloaded binary, open file COMMIT_HASH from the main folder and paste the content in the issue description**

![wow_db_version](https://user-images.githubusercontent.com/640311/162265594-c16a3563-95cb-4f2e-a2f6-e91c5e9ce3b9.jpg)

**Comment by gonzo1247** [comment]
the editor looks like he has problems to load the DBC data.

> System.AggregateException: One or more errors occurred. (The given key '3419' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key '3419' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WDE.DbcStore.DbcStore.DbcLoadTask.BuildAreaGroupName(IDbcIterator row, Int32 start, Int32 count)
   at WDE.DbcStore.DbcStore.DbcLoadTask.<Run>b__170_15(IDbcIterator row)
   at WDE.DbcStore.DbcStore.DbcLoadTask.Load(String filename, Action`1 foreachRow)
   at WDE.DbcStore.DbcStore.DbcLoadTask.Run(ITaskProgress progress)
   at WoWDatabaseEditorCore.Tasks.TaskRunner.<>c__DisplayClass17_0.<ScheduleNow>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
An item with the same key has already been added. Key: 0
System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at WDE.Parameters.CreatureGameobjectParameter.LateLoad()
   at WDE.Parameters.ParameterLoader.<>c__DisplayClass10_0.<Load>b__4(ILoadingEvent _)
   at WDE.MVVM.Observable.DelegateObserver`1.OnNext(T value)
   at WDE.MVVM.Observable.OnDemandSingleValuePublisher`1.Subscription.FireAndComplete(T value)
   at WDE.MVVM.Observable.OnDemandSingleValuePublisher`1.Publish(T value)
   at WoWDatabaseEditorCore.Services.LoadingEvents.LoadingEventAggregator.Publish[T]()
   at WDE.MySqlDatabaseCommon.Database.World.CachedDatabaseProvider.DatabaseCacheTask.Run(ITaskProgress progress)
   at WoWDatabaseEditorCore.Tasks.TaskRunner.<>c__DisplayClass17_2.<<ScheduleNow>b__3>d.MoveNext()
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at WDE.Parameters.CreatureGameobjectParameter.LateLoad()
   at WDE.Parameters.ParameterLoader.<>c__DisplayClass10_0.<Load>b__4(ILoadingEvent _)
   at WDE.MVVM.Observable.DelegateObserver`1.OnNext(T value)
   at WDE.MVVM.Observable.OnDemandSingleValuePublisher`1.Subscription.FireAndComplete(T value)
   at WDE.MVVM.Observable.OnDemandSingleValuePublisher`1.Publish(T value)
   at WoWDatabaseEditorCore.Services.LoadingEvents.LoadingEventAggregator.Publish[T]()
   at WDE.MySqlDatabaseCommon.Database.World.CachedDatabaseProvider.DatabaseCacheTask.Run(ITaskProgress progress)
   at WoWDatabaseEditorCore.Tasks.TaskRunner.<>c__DisplayClass17_2.<<ScheduleNow>b__3>d.MoveNext()

>

**Comment by BAndysc** [comment]
What DBC version are you using?

**Comment by gonzo1247** [comment]
enUS 15595
but has try it with deDE 15595

**Comment by BAndysc** [comment]
Fixed
