### ISSUE TITLE
Negative Creature id crashes client

### ISSUE THREAD

**Issue by Furioz420** [BAndysc/WoWDatabaseEditor#174]
I was doing some SAI coding, and wanted to create a script for a creature using their guid instead of CreatureID.

So i used a negative value (-3111194) and when it tryed to go into the creaturescript itself , it crashed. This keep occuring whenever i try to load anything in the program now. 

COMMIT=04c0c7d6406d2d117afb921d7810928b913daddf  
BRANCH=master  
VERSION=0.1.1962  
BUILD_VERSION=1962  
UPDATE_SERVER=https://dbeditor.ovh  
MARKETPLACE=default  
MAPDATA_SERVER=https://dbeditor.ovh 
PLATFORM=Windows 

**To Reproduce**
1. Click on creaturescript
2. Add the value of -3111194
3. confirm the value and let the client load the creaturescript
4. Client will halt & crash

**Expected behavior**
Well like it does with other creatures, simply load the creaturescript.  This creature had no script or data attached to it so the problem cant be that.

Crash.log
MySqlConnector.MySqlException (0x80004005): Unknown column 'c_1.modelid' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 119
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 315
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 256
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass4_0`1.<GetFirstOrDefaultElement>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at WDE.TrinityMySqlDatabase.Database.AzerothhMySqlDatabaseProvider.GetCreatureByGuid(UInt32 guid)
   at WDE.SmartScriptEditor.Providers.SmartScriptNameProviderBase`1.TryGetName(Int32 entryOrGuid, SmartScriptType type)
   at WDE.SmartScriptEditor.Providers.SmartScriptNameProviderBase`1.GetName(T item)
   at WDE.TrinitySmartScriptEditor.Providers.SmartScriptNameProvider.GetName(SmartScriptSolutionItem item)
   at WDE.Solutions.Manager.SolutionItemNameRegistry.GetName[T](T item)
   at WDE.Solutions.Manager.SolutionItemNameRegistry.GetName(ISolutionItem item)
   at WoWDatabaseEditorCore.ViewModels.QuickStartViewModel.ReloadMruList()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 278
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 132
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 187
   at WoWDatabaseEditorCore.Avalonia.Program.Main(String[] args)

**Comment by Furioz420** [comment]
A "quick fix" is deleted the wowdatabaseeditor folder in /appdata/local/ and redoing the first time wizard etc.

**Comment by BAndysc** [comment]
it wasn't a problem with negative id, there was a database compatibility issue, will work now
