### ISSUE TITLE
Software Not Open

### ISSUE THREAD

**Issue by tunitoo0** [BAndysc/WoWDatabaseEditor#203]
When i try to start the program, its just stay in Loading Screen. Have download the latest version of software.
![image](https://github.com/BAndysc/WoWDatabaseEditor/assets/37191486/db8bcfef-81b0-4849-b9b5-bbe5806d114d)

**Comment by BAndysc** [comment]
Please open CrashReport.exe, then press right mouse button on the "restart the editor"  button to open the menu and choose "restart the editor with console". Now a black console window should pop up. Please copy its content and paste here

**Comment by tunitoo0** [comment]
There is noting to paste like 10 mins its black console :/
![image](https://github.com/BAndysc/WoWDatabaseEditor/assets/37191486/d7f85ce3-6968-4766-9b88-8dcd79499073)

**Comment by BAndysc** [comment]
Are you using the latest TrinityCore/AzerothCore database and the official unmodified DBC?

**Comment by tunitoo0** [comment]
Yes i use trinitycore, before a day this sowftware work perfectly but yesterday idk why when i try to start it, noting.

**Comment by tunitoo0** [comment]
And i redownload the program again, for try without adding the paths for server, again the program not opening.

**Comment by heyitsbench** [comment]
I am getting [this error](https://github.com/BAndysc/WoWDatabaseEditor/assets/38561765/9325ad3d-47a5-4ad9-b76d-88f84c81d40d) on a clean download of the [latest release](https://github.com/BAndysc/WoWDatabaseEditor/releases/tag/build2397).
```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at WDE.DbcStore.Spells.Wrath.WrathSpellService.get_SpellCount()
   at WDE.DbcStore.DbcStore.get_SpellCount()
   at WDE.Spells.MergedSpellService.Cache()
   at WDE.Spells.MergedSpellService.<.ctor>b__3_0(ISpellService _)
   at WDE.Spells.DatabaseSpellService.LoadDataAsync()
   --- End of inner exception stack trace ---
```
