### ISSUE TITLE
Program crash during program setup - customization

### ISSUE THREAD

**Issue by shamage** [BAndysc/WoWDatabaseEditor#209]
**Describe the bug**
I was setting the parameters in the program and suddenly this:
Crash log : 
System.InvalidOperationException: Unable to create child window for native control host. Application manifest with supported OS list might be required.
   at Avalonia.Win32.Win32NativeControlHost.DumbWindow..ctor(Boolean layered, Nullable`1 parent) in /_/src/Windows/Avalonia.Win32/Win32NativeControlHost.cs:line 99
   at Avalonia.Win32.Win32NativeControlHost.CreateNewAttachment(Func`2 create) in /_/src/Windows/Avalonia.Win32/Win32NativeControlHost.cs:line 35
   at Avalonia.Controls.NativeControlHost.UpdateHost() in /_/src/Avalonia.Controls/NativeControlHost.cs:line 95
   at Avalonia.Controls.NativeControlHost.OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/NativeControlHost.cs:line 35
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Visuals/Visual.cs:line 421
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Layout/Layoutable.cs:line 757
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 176
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Visuals/Visual.cs:line 421
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Layout/Layoutable.cs:line 757
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 176
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Visuals/Visual.cs:line 421
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Layout/Layoutable.cs:line 757
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 176
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Visuals/Visual.cs:line 421
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Layout/Layoutable.cs:line 757
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 176
   at Avalonia.Visual.SetVisualParent(Visual value) in /_/src/Avalonia.Visuals/Visual.cs:line 586
   at Avalonia.Visual.SetVisualParent(IList children, Visual parent) in /_/src/Avalonia.Visuals/Visual.cs:line 646
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 691
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild() in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 302
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 589
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 613
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 589
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 366
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 589
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 285
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 264
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 251
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 171
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 217
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at WoWDatabaseEditorCore.Avalonia.Program.Main(String[] args) in F:\source\WoWDatabaseEditor\WoWDatabaseEditorCore.Avalonia\Program.cs:line 36

unknown app data

**Version (commit hash)**
2024.1  [0bfb250](https://github.com/BAndysc/WoWDatabaseEditor/commit/0bfb25081a54956bc26a936e832a47667b8027a7)

If you have built the binary yourself, check commit hash with `git rev-parse HEAD`

**To Reproduce**
1. Go to program settings - customization of tables

**Expected behavior**
the program should not crash

**Screenshots**
![Ashampoo_Snap_streda 24  januára 2024_12h11m4s](https://github.com/BAndysc/WoWDatabaseEditor/assets/7515044/d2e9fe35-a01c-4ee8-93af-80a1a842963c)

**Comment by BAndysc** [comment]
Fixed now
