### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by fangshun2004** [BAndysc/WoWDatabaseEditor#217]
**Describe the bug**

WDE.Common.Services.DataMissingException: Couldn't read file CodeCompletionData
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\WoWDatabaseEditor\CodeCompletionData'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at WoWDatabaseEditorCore.Services.RuntimeData.LocalRuntimeDataService.GetAllFiles(String directory, String searchPattern)
   --- End of inner exception stack trace ---
   at WoWDatabaseEditorCore.Services.RuntimeData.LocalRuntimeDataService.GetAllFiles(String directory, String searchPattern)
   at WDE.Common.Avalonia.Controls.CodeCompletionTextEditor.CodeCompletionService.Initialize()
   at WoWDatabaseEditorCore.Avalonia.App.OnInitializedAsync()
   at WoWDatabaseEditorCore.Avalonia.App.OnFrameworkInitializationCompletedAsync()
   at WoWDatabaseEditorCore.Avalonia.App.<OnFrameworkInitializationCompleted>g__Load|23_0()

COMMIT=8128b212452739439a24d2753ebf63fef56c720e
BRANCH=master
VERSION=0.1.2646
BUILD_VERSION=2646
UPDATE_SERVER=
MARKETPLACE=default
MAPDATA_SERVER=
PLATFORM=Windows

**Version (commit hash)**
Please include what was the WoW Database Editor version (commit hash). **If you downloaded binary, open file COMMIT_HASH from the main folder and paste the content in the issue description**

If you have built the binary yourself, check commit hash with `git rev-parse HEAD`

8128b212452739439a24d2753ebf63fef56c720e

**To Reproduce**
1. Run WoWDatabaseEditorCore.Avalonia.exe
2. See error

**Expected behavior**
Open the editing interface

**Screenshots**
![image](https://github.com/BAndysc/WoWDatabaseEditor/assets/49193927/fd5dee24-369d-499f-ac24-d55ecd1d0219)

**Comment by fangshun2004** [comment]
There is a problem with the source of the link to the download in the homepage. Downloading from the release page is ready to run

**Comment by BAndysc** [comment]
The home page download link should now work as well, thanks for the report.
