### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by Bestboii** [BAndysc/WoWDatabaseEditor#234]
**Describe the bug**
Whenever i open the DBEditor it crashes immediately. Same thing happens when i click on "Download the latest version" in the Crash Report, after the download is complete i get the same Error.

**Version (commit hash)**
VERSION=0.1.2845
BUILD_VERSION=2845

No problems on version 2659

**Error**
```
System.ArgumentException: An item with the same key has already been added. Key: 2804
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at WDE.DbcStore.DbcStore.DbcLoadTask.FinishMainThread()
   at WoWDatabaseEditorCore.Tasks.TaskRunner.<>c__DisplayClass18_1.<ScheduleNow>b__2()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at BaseDesktopLoader.BaseProgramLoader.Main(Type[] modules, String[] args)

COMMIT=5e0b1352c813aa98fa0ec95b52d56783c8baec2e
BRANCH=master
VERSION=0.1.2845
BUILD_VERSION=2845
UPDATE_SERVER=https://dbeditor.ovh
MARKETPLACE=default
MAPDATA_SERVER=https://dbeditor.ovh
PLATFORM=Windows

```

**Comment by Bestboii** [comment]
The error still persists on the current version:
`System.ArgumentException: An item with the same key has already been added. Key: 2804
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at WDE.DbcStore.DbcStore.DbcLoadTask.FinishMainThread()
   at WoWDatabaseEditorCore.Tasks.TaskRunner.<>c__DisplayClass18_1.<ScheduleNow>b__2()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32DispatcherImpl.DispatchWorkItem()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at BaseDesktopLoader.BaseProgramLoader.Main(Type[] modules, String[] args)

COMMIT=a8148623a2857ccf8e6881a2f27fdd382fbe8f12
BRANCH=master
VERSION=0.1.2922
BUILD_VERSION=2922
UPDATE_SERVER=https://dbeditor.ovh
MARKETPLACE=default
MAPDATA_SERVER=https://dbeditor.ovh
PLATFORM=Windows
`

**Comment by Bestboii** [comment]
I finally found the problem.

I had to delete the 'WoWDatabaseEditor' folder under `%appdata%/.../Local/WoWDatabaseEditor`.

After this, i finally could open the latest version.
